In [2]:
import datetime
import requests as re
import pandas as pd
import json
import csv
import time
import datetime
from datetime import date
#d = datetime.date(2020,1,4)


today = date.today()
print(today)
d = datetime.date.today()
unixtime = time.mktime(d.timetuple())
print(unixtime)

#api2 = ("http://api.openweathermap.org/data/2.5/onecall/timemachine?lat=45.187604404569896&lon=5.704903862324499&units=metric&lang=fr&dt=1618992000&APPID=053c09565de3a966efa5b8d39b2969d9")

api2 = "http://api.openweathermap.org/data/2.5/onecall/timemachine?"
params = {
       'lat': '45.187604404569896',
       'lon': '5.704903862324499',
       'type': 'hour',
       'units': 'metric',
       'dt':  str(int(unixtime)),
       'lang': 'fr',
       'appid': '053c09565de3a966efa5b8d39b2969d9'
}

response = re.request("GET", api2, params=params)
print(response.text)

2021-04-26
1619388000.0
{"lat":45.1876,"lon":5.7049,"timezone":"Europe/Paris","timezone_offset":7200,"current":{"dt":1619388000,"sunrise":1619411612,"sunset":1619462166,"temp":13.26,"feels_like":11.25,"pressure":1013,"humidity":54,"dew_point":4.16,"uvi":7.36,"clouds":0,"visibility":10000,"wind_speed":1.03,"wind_deg":0,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01n"}]},"hourly":[{"dt":1619308800,"temp":10.41,"feels_like":7.21,"pressure":1018,"humidity":54,"dew_point":1.51,"clouds":0,"visibility":10000,"wind_speed":2.06,"wind_deg":240,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01n"}]},{"dt":1619312400,"temp":10.22,"feels_like":7.69,"pressure":1018,"humidity":62,"dew_point":3.27,"clouds":0,"visibility":10000,"wind_speed":1.54,"wind_deg":0,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01n"}]},{"dt":1619316000,"temp":9.14,"feels_like":7.16,"pressure":1018,"humidity":81,"dew_point":6.06,"clouds":0,"visibility":10000,"wind_speed":1.54,"wind_deg":0,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01n"}]},{"dt":1619319600,"temp":8.73,"feels_like":5.8,"pressure":1017,"humidity":87,"dew_point":6.69,"clouds":0,"visibility":10000,"wind_speed":3.09,"wind_deg":80,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01n"}]},{"dt":1619323200,"temp":8.36,"feels_like":5.35,"pressure":1017,"humidity":87,"dew_point":6.33,"clouds":0,"visibility":10000,"wind_speed":3.09,"wind_deg":100,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01n"}]},{"dt":1619326800,"temp":8.13,"feels_like":4.71,"pressure":1017,"humidity":87,"dew_point":6.1,"clouds":0,"visibility":10000,"wind_speed":3.6,"wind_deg":70,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619330400,"temp":10.48,"feels_like":7.7,"pressure":1017,"humidity":81,"dew_point":7.36,"clouds":0,"visibility":10000,"wind_speed":3.09,"wind_deg":90,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619334000,"temp":13.12,"feels_like":9.32,"pressure":1017,"humidity":62,"dew_point":6.01,"clouds":0,"visibility":10000,"wind_speed":4.12,"wind_deg":70,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619337600,"temp":15.02,"feels_like":11.59,"pressure":1016,"humidity":55,"dew_point":6.06,"clouds":0,"visibility":10000,"wind_speed":3.6,"wind_deg":70,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619341200,"temp":16.7,"feels_like":13.72,"pressure":1017,"humidity":45,"dew_point":4.72,"clouds":0,"visibility":10000,"wind_speed":2.57,"wind_deg":70,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619344800,"temp":18.31,"feels_like":15.64,"pressure":1016,"humidity":40,"dew_point":4.49,"clouds":0,"visibility":10000,"wind_speed":2.06,"wind_deg":110,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619348400,"temp":19.27,"feels_like":16.77,"pressure":1016,"humidity":35,"dew_point":3.45,"clouds":0,"visibility":10000,"wind_speed":1.54,"wind_deg":0,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619352000,"temp":20.04,"feels_like":18.05,"pressure":1016,"humidity":40,"dew_point":6.04,"clouds":0,"visibility":10000,"wind_speed":1.54,"wind_deg":0,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619355600,"temp":20.89,"feels_like":17.94,"pressure":1015,"humidity":35,"dew_point":4.87,"clouds":0,"visibility":10000,"wind_speed":2.57,"wind_deg":220,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619359200,"temp":21.04,"feels_like":18.47,"pressure":1014,"humidity":35,"dew_point":5.01,"clouds":0,"visibility":10000,"wind_speed":2.06,"wind_deg":250,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619362800,"temp":20.36,"feels_like":17.94,"pressure":1013,"humidity":43,"dew_point":7.38,"clouds":0,"visibility":10000,"wind_speed":2.57,"wind_deg":220,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619366400,"temp":19.78,"feels_like":15.58,"pressure":1013,"humidity":40,"dew_point":5.81,"clouds":0,"visibility":10000,"wind_speed":4.63,"wind_deg":230,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619370000,"temp":18.83,"feels_like":15.46,"pressure":1013,"humidity":39,"dew_point":4.6,"clouds":0,"visibility":10000,"wind_speed":3.09,"wind_deg":230,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619373600,"temp":16.37,"feels_like":13.32,"pressure":1012,"humidity":39,"dew_point":2.4,"clouds":0,"visibility":10000,"wind_speed":2.06,"wind_deg":250,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619377200,"temp":15.18,"feels_like":12.43,"pressure":1013,"humidity":41,"dew_point":2.03,"clouds":0,"visibility":10000,"wind_speed":1.54,"wind_deg":0,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01n"}]},{"dt":1619380800,"temp":14.18,"feels_like":12.54,"pressure":1014,"humidity":51,"dew_point":4.2,"clouds":0,"visibility":10000,"wind_speed":0.51,"wind_deg":0,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01n"}]},{"dt":1619384400,"temp":14.01,"feels_like":11.62,"pressure":1013,"humidity":51,"dew_point":4.04,"clouds":0,"visibility":10000,"wind_speed":1.54,"wind_deg":260,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01n"}]},{"dt":1619388000,"temp":13.26,"feels_like":11.25,"pressure":1013,"humidity":54,"dew_point":4.16,"clouds":0,"visibility":10000,"wind_speed":1.03,"wind_deg":0,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01n"}]},{"dt":1619391600,"temp":12.79,"feels_like":11.17,"pressure":1013,"humidity":71,"dew_point":7.67,"clouds":99,"visibility":10000,"wind_speed":1.54,"wind_deg":80,"weather":[{"id":804,"main":"Clouds","description":"couvert","icon":"04n"}]}]}

In [316]:
response.text 
data_dict = response.json()

In [317]:
with open("data_file.json", "w") as write_file:
    json.dump(data_dict, write_file)

In [318]:
print(data_dict['current']['dt'], data_dict['current']['temp'])

1618963200 7.61

In [319]:
df1 = pd.json_normalize(data_dict['hourly'])

In [320]:
df1.dt

0     1618963200
1     1618966800
2     1618970400
3     1618974000
4     1618977600
5     1618981200
6     1618984800
7     1618988400
8     1618992000
9     1618995600
10    1618999200
11    1619002800
12    1619006400
13    1619010000
14    1619013600
15    1619017200
16    1619020800
17    1619024400
18    1619028000
19    1619031600
20    1619035200
21    1619038800
22    1619042400
23    1619046000
Name: dt, dtype: int64

In [321]:
df1.dt = pd.to_datetime(df1['dt'],unit='s')

In [322]:
df1.dt

0    2021-04-21 00:00:00
1    2021-04-21 01:00:00
2    2021-04-21 02:00:00
3    2021-04-21 03:00:00
4    2021-04-21 04:00:00
5    2021-04-21 05:00:00
6    2021-04-21 06:00:00
7    2021-04-21 07:00:00
8    2021-04-21 08:00:00
9    2021-04-21 09:00:00
10   2021-04-21 10:00:00
11   2021-04-21 11:00:00
12   2021-04-21 12:00:00
13   2021-04-21 13:00:00
14   2021-04-21 14:00:00
15   2021-04-21 15:00:00
16   2021-04-21 16:00:00
17   2021-04-21 17:00:00
18   2021-04-21 18:00:00
19   2021-04-21 19:00:00
20   2021-04-21 20:00:00
21   2021-04-21 21:00:00
22   2021-04-21 22:00:00
23   2021-04-21 23:00:00
Name: dt, dtype: datetime64[ns]

In [323]:
df1

,dt,temp,feels_like,pressure,humidity,dew_point,clouds,visibility,wind_speed,wind_deg,weather,rain.1h
0,2021-04-21 00:00:00,7.61,4.67,1014,62,0.80,0,10000,1.54,260,"[{'id': 800, 'main': 'Clear', 'description': '...",NaN
1,2021-04-21 01:00:00,7.50,4.68,1014,66,1.57,90,10000,1.54,0,"[{'id': 804, 'main': 'Clouds', 'description': ...",NaN
2,2021-04-21 02:00:00,8.25,5.36,1014,71,3.31,90,10000,2.06,330,"[{'id': 500, 'main': 'Rain', 'description': 'l...",0.76
3,2021-04-21 03:00:00,7.89,4.93,1014,81,4.84,0,10000,2.57,90,"[{'id': 500, 'main': 'Rain', 'description': 'l...",0.51
4,2021-04-21 04:00:00,7.86,4.53,1014,81,4.81,0,10000,3.09,60,"[{'id': 500, 'main': 'Rain', 'description': 'l...",0.51
5,2021-04-21 05:00:00,7.67,2.72,1015,87,5.65,0,10000,5.66,70,"[{'id': 800, 'main': 'Clear', 'description': '...",NaN
6,2021-04-21 06:00:00,7.56,5.82,1015,87,5.54,0,10000,1.03,0,"[{'id': 800, 'main': 'Clear', 'description': '...",NaN
7,2021-04-21 07:00:00,8.12,5.03,1015,76,4.15,0,10000,2.57,90,"[{'id': 800, 'main': 'Clear', 'description': '...",NaN
8,2021-04-21 08:00:00,10.59,8.48,1016,62,3.62,75,10000,1.03,0,"[{'id': 803, 'main': 'Clouds', 'description': ...",NaN
9,2021-04-21 09:00:00,11.21,8.50,1016,54,2.25,75,10000,1.54,330,"[{'id': 803, 'main': 'Clouds', 'description': ...",NaN
10,2021-04-21 10:00:00,12.91,10.84,1015,54,3.84,90,10000,1.03,0,"[{'id': 804, 'main': 'Clouds', 'description': ...",NaN
11,2021-04-21 11:00:00,11.66,9.61,1015,51,1.87,75,10000,0.51,0,"[{'id': 501, 'main': 'Rain', 'description': 'p...",1.02
12,2021-04-21 12:00:00,12.30,9.96,1015,58,4.28,75,10000,1.54,280,"[{'id': 500, 'main': 'Rain', 'description': 'l...",0.43
13,2021-04-21 13:00:00,12.84,10.76,1015,54,3.77,75,10000,1.03,0,"[{'id': 803, 'main': 'Clouds', 'description': ...",NaN
14,2021-04-21 14:00:00,12.40,9.38,1014,51,2.56,0,10000,2.06,330,"[{'id': 800, 'main': 'Clear', 'description': '...",NaN
15,2021-04-21 15:00:00,12.40,9.38,1014,51,2.56,96,10000,2.06,350,"[{'id': 500, 'main': 'Rain', 'description': 'l...",0.42
16,2021-04-21 16:00:00,12.34,8.42,1014,55,3.57,75,10000,3.60,290,"[{'id': 803, 'main': 'Clouds', 'description': ...",NaN
17,2021-04-21 17:00:00,11.56,8.18,1014,54,2.58,75,10000,2.57,10,"[{'id': 803, 'main': 'Clouds', 'description': ...",NaN
18,2021-04-21 18:00:00,9.78,7.45,1015,87,7.72,90,10000,2.57,280,"[{'id': 500, 'main': 'Rain', 'description': 'l...",0.26
19,2021-04-21 19:00:00,8.76,6.70,1016,81,5.68,90,10000,1.54,90,"[{'id': 804, 'main': 'Clouds', 'description': ...",NaN
20,2021-04-21 20:00:00,8.27,5.96,1016,87,6.24,90,10000,2.06,90,"[{'id': 804, 'main': 'Clouds', 'description': ...",NaN
21,2021-04-21 21:00:00,7.68,5.97,1016,87,5.66,90,10000,1.03,140,"[{'id': 804, 'main': 'Clouds', 'description': ...",NaN
22,2021-04-21 22:00:00,7.57,5.32,1017,93,6.51,90,10000,2.06,70,"[{'id': 804, 'main': 'Clouds', 'description': ...",NaN
23,2021-04-21 23:00:00,6.92,4.70,1017,87,4.91,75,10000,1.54,90,"[{'id': 803, 'main': 'Clouds', 'description': ...",NaN

In [328]:
with open(r"temp_ext.csv", "a") as f:
    df1.to_csv(f, header=f.tell()==0, index = True) #La méthode tell() de l’objet fichier retourne la position actuelle du curseur. Par conséquent, si le fichier est vide ou n’existe pas, f.tell==0 est True, de sorte que header est mis à True ; sinon, header est mis à False.