In [8]:
import datetime
import requests as re
import pandas as pd
import json
import csv
import time
import datetime
from datetime import date
#d = datetime.date(2020,1,4)


#today = date.today()
#print(today)
#d = datetime.date.today()
#unixtime = time.mktime(d.timetuple())

unixtime = 1619049600
print(unixtime)

#api2 = ("http://api.openweathermap.org/data/2.5/onecall/timemachine?lat=45.187604404569896&lon=5.704903862324499&units=metric&lang=fr&dt=1618992000&APPID=053c09565de3a966efa5b8d39b2969d9")

api2 = "http://api.openweathermap.org/data/2.5/onecall/timemachine?"
params = {
       'lat': '45.187604404569896',
       'lon': '5.704903862324499',
       'type': 'hour',
       'units': 'metric',
       'dt':  str(int(unixtime)),
       'lang': 'fr',
       'appid': '053c09565de3a966efa5b8d39b2969d9'
}

response = re.request("GET", api2, params=params)
print(response.text)

1619049600
{"lat":45.1876,"lon":5.7049,"timezone":"Europe/Paris","timezone_offset":7200,"current":{"dt":1619049600,"sunrise":1619066399,"sunset":1619116259,"temp":10.19,"feels_like":9.42,"pressure":1019,"humidity":88,"dew_point":8.29,"uvi":5.56,"clouds":38,"wind_speed":0.53,"wind_deg":81,"wind_gust":0.78,"weather":[{"id":802,"main":"Clouds","description":"partiellement nuageux","icon":"03n"}]},"hourly":[{"dt":1619049600,"temp":10.19,"feels_like":9.42,"pressure":1019,"humidity":88,"dew_point":8.29,"clouds":38,"wind_speed":0.53,"wind_deg":81,"wind_gust":0.78,"weather":[{"id":802,"main":"Clouds","description":"partiellement nuageux","icon":"03n"}]},{"dt":1619053200,"temp":10.19,"feels_like":9.42,"pressure":1019,"humidity":88,"dew_point":8.29,"clouds":38,"wind_speed":0.53,"wind_deg":81,"wind_gust":0.78,"weather":[{"id":802,"main":"Clouds","description":"partiellement nuageux","icon":"03n"}]},{"dt":1619056800,"temp":10.19,"feels_like":9.42,"pressure":1019,"humidity":88,"dew_point":8.29,"clouds":38,"wind_speed":0.53,"wind_deg":81,"wind_gust":0.78,"weather":[{"id":802,"main":"Clouds","description":"partiellement nuageux","icon":"03n"}]},{"dt":1619060400,"temp":10.19,"feels_like":9.42,"pressure":1019,"humidity":88,"dew_point":8.29,"clouds":38,"wind_speed":0.53,"wind_deg":81,"wind_gust":0.78,"weather":[{"id":802,"main":"Clouds","description":"partiellement nuageux","icon":"03n"}]},{"dt":1619064000,"temp":10.19,"feels_like":9.42,"pressure":1019,"humidity":88,"dew_point":8.29,"clouds":38,"wind_speed":0.53,"wind_deg":81,"wind_gust":0.78,"weather":[{"id":802,"main":"Clouds","description":"partiellement nuageux","icon":"03n"}]},{"dt":1619067600,"temp":10.19,"feels_like":9.42,"pressure":1019,"humidity":88,"dew_point":8.29,"clouds":38,"wind_speed":0.53,"wind_deg":81,"wind_gust":0.78,"weather":[{"id":802,"main":"Clouds","description":"partiellement nuageux","icon":"03d"}]},{"dt":1619071200,"temp":10.19,"feels_like":9.42,"pressure":1019,"humidity":88,"dew_point":8.29,"clouds":38,"wind_speed":0.53,"wind_deg":81,"wind_gust":0.78,"weather":[{"id":802,"main":"Clouds","description":"partiellement nuageux","icon":"03d"}]},{"dt":1619074800,"temp":11.86,"feels_like":11.07,"pressure":1019,"humidity":80,"dew_point":8.52,"clouds":46,"wind_speed":0.65,"wind_deg":15,"wind_gust":1.13,"weather":[{"id":802,"main":"Clouds","description":"partiellement nuageux","icon":"03d"}]},{"dt":1619078400,"temp":13.55,"feels_like":12.3,"pressure":1018,"humidity":72,"dew_point":8.61,"clouds":41,"wind_speed":1.33,"wind_deg":356,"wind_gust":1.92,"weather":[{"id":802,"main":"Clouds","description":"partiellement nuageux","icon":"03d"}]},{"dt":1619082000,"temp":15.24,"feels_like":13.58,"pressure":1018,"humidity":62,"dew_point":8.01,"clouds":35,"wind_speed":1.71,"wind_deg":348,"wind_gust":1.84,"weather":[{"id":802,"main":"Clouds","description":"partiellement nuageux","icon":"03d"}]},{"dt":1619085600,"temp":16.75,"feels_like":14.92,"pressure":1018,"humidity":54,"dew_point":7.4,"clouds":31,"wind_speed":1.75,"wind_deg":338,"wind_gust":1.73,"weather":[{"id":802,"main":"Clouds","description":"partiellement nuageux","icon":"03d"}]},{"dt":1619089200,"temp":17.35,"feels_like":15.41,"pressure":1017,"humidity":51,"dew_point":7.12,"clouds":37,"wind_speed":1.81,"wind_deg":323,"wind_gust":1.88,"weather":[{"id":802,"main":"Clouds","description":"partiellement nuageux","icon":"03d"}]},{"dt":1619092800,"temp":17.02,"feels_like":14.91,"pressure":1018,"humidity":51,"dew_point":6.82,"clouds":98,"wind_speed":1.95,"wind_deg":310,"wind_gust":1.8,"weather":[{"id":804,"main":"Clouds","description":"couvert","icon":"04d"}]},{"dt":1619096400,"temp":16.63,"feels_like":14.67,"pressure":1018,"humidity":55,"dew_point":7.56,"clouds":99,"wind_speed":1.98,"wind_deg":311,"wind_gust":2.04,"weather":[{"id":804,"main":"Clouds","description":"couvert","icon":"04d"}]},{"dt":1619100000,"temp":16.88,"feels_like":15.12,"pressure":1017,"humidity":55,"dew_point":7.79,"clouds":98,"wind_speed":1.77,"wind_deg":318,"wind_gust":2.26,"weather":[{"id":804,"main":"Clouds","description":"couvert","icon":"04d"}]},{"dt":1619103600,"temp":17.42,"feels_like":15.71,"pressure":1017,"humidity":53,"dew_point":7.75,"clouds":97,"wind_speed":1.69,"wind_deg":325,"wind_gust":2.57,"weather":[{"id":804,"main":"Clouds","description":"couvert","icon":"04d"}]},{"dt":1619107200,"temp":17.23,"feels_like":15.42,"pressure":1017,"humidity":55,"dew_point":8.12,"clouds":92,"wind_speed":1.96,"wind_deg":333,"wind_gust":2.94,"weather":[{"id":804,"main":"Clouds","description":"couvert","icon":"04d"}]},{"dt":1619110800,"temp":16.49,"feels_like":11.12,"pressure":1016,"humidity":42,"dew_point":3.55,"clouds":0,"visibility":10000,"wind_speed":5.66,"wind_deg":340,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619114400,"temp":14.71,"feels_like":11.56,"pressure":1017,"humidity":48,"dew_point":3.83,"clouds":0,"visibility":10000,"wind_speed":2.57,"wind_deg":340,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01d"}]},{"dt":1619118000,"temp":12.36,"feels_like":10.75,"pressure":1017,"humidity":58,"dew_point":4.34,"clouds":0,"visibility":10000,"wind_speed":0.51,"wind_deg":0,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01n"}]},{"dt":1619121600,"temp":10.51,"feels_like":8.75,"pressure":1018,"humidity":62,"dew_point":3.55,"clouds":0,"visibility":10000,"wind_speed":0.51,"wind_deg":0,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01n"}]},{"dt":1619125200,"temp":8.86,"feels_like":6.44,"pressure":1018,"humidity":71,"dew_point":3.9,"clouds":0,"visibility":10000,"wind_speed":1.54,"wind_deg":120,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01n"}]},{"dt":1619128800,"temp":7.8,"feels_like":5.18,"pressure":1019,"humidity":81,"dew_point":4.75,"clouds":0,"visibility":10000,"wind_speed":2.06,"wind_deg":110,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01n"}]},{"dt":1619132400,"temp":7.11,"feels_like":4.21,"pressure":1019,"humidity":87,"dew_point":5.1,"clouds":0,"visibility":10000,"wind_speed":2.57,"wind_deg":90,"weather":[{"id":800,"main":"Clear","description":"ciel dégagé","icon":"01n"}]}]}

In [9]:
response.text 
data_dict = response.json()

In [10]:
with open("data_file_1.json", "w") as write_file:
    json.dump(data_dict, write_file)

In [11]:
print(data_dict['current']['dt'], data_dict['current']['temp'])

1619049600 10.19

In [12]:
df1 = pd.json_normalize(data_dict['hourly'])

In [13]:
df1.dt

0     1619049600
1     1619053200
2     1619056800
3     1619060400
4     1619064000
5     1619067600
6     1619071200
7     1619074800
8     1619078400
9     1619082000
10    1619085600
11    1619089200
12    1619092800
13    1619096400
14    1619100000
15    1619103600
16    1619107200
17    1619110800
18    1619114400
19    1619118000
20    1619121600
21    1619125200
22    1619128800
23    1619132400
Name: dt, dtype: int64

In [14]:
df1.dt = pd.to_datetime(df1['dt'],unit='s') # convertion unixtime en datetime

In [15]:
df1.dt

0    2021-04-22 00:00:00
1    2021-04-22 01:00:00
2    2021-04-22 02:00:00
3    2021-04-22 03:00:00
4    2021-04-22 04:00:00
5    2021-04-22 05:00:00
6    2021-04-22 06:00:00
7    2021-04-22 07:00:00
8    2021-04-22 08:00:00
9    2021-04-22 09:00:00
10   2021-04-22 10:00:00
11   2021-04-22 11:00:00
12   2021-04-22 12:00:00
13   2021-04-22 13:00:00
14   2021-04-22 14:00:00
15   2021-04-22 15:00:00
16   2021-04-22 16:00:00
17   2021-04-22 17:00:00
18   2021-04-22 18:00:00
19   2021-04-22 19:00:00
20   2021-04-22 20:00:00
21   2021-04-22 21:00:00
22   2021-04-22 22:00:00
23   2021-04-22 23:00:00
Name: dt, dtype: datetime64[ns]

In [66]:
df1

,dt,temp,feels_like,pressure,humidity,dew_point,clouds,visibility,wind_speed,wind_deg,weather
0,2021-04-25 00:00:00,10.41,7.21,1018,54,1.51,0,10000,2.06,240,"[{'id': 800, 'main': 'Clear', 'description': '..."
1,2021-04-25 01:00:00,10.22,7.69,1018,62,3.27,0,10000,1.54,0,"[{'id': 800, 'main': 'Clear', 'description': '..."
2,2021-04-25 02:00:00,9.14,7.16,1018,81,6.06,0,10000,1.54,0,"[{'id': 800, 'main': 'Clear', 'description': '..."
3,2021-04-25 03:00:00,8.73,5.80,1017,87,6.69,0,10000,3.09,80,"[{'id': 800, 'main': 'Clear', 'description': '..."
4,2021-04-25 04:00:00,8.36,5.35,1017,87,6.33,0,10000,3.09,100,"[{'id': 800, 'main': 'Clear', 'description': '..."
5,2021-04-25 05:00:00,8.13,4.71,1017,87,6.10,0,10000,3.60,70,"[{'id': 800, 'main': 'Clear', 'description': '..."
6,2021-04-25 06:00:00,10.48,7.70,1017,81,7.36,0,10000,3.09,90,"[{'id': 800, 'main': 'Clear', 'description': '..."
7,2021-04-25 07:00:00,13.12,9.32,1017,62,6.01,0,10000,4.12,70,"[{'id': 800, 'main': 'Clear', 'description': '..."
8,2021-04-25 08:00:00,15.02,11.59,1016,55,6.06,0,10000,3.60,70,"[{'id': 800, 'main': 'Clear', 'description': '..."
9,2021-04-25 09:00:00,16.70,13.72,1017,45,4.72,0,10000,2.57,70,"[{'id': 800, 'main': 'Clear', 'description': '..."
10,2021-04-25 10:00:00,18.31,15.64,1016,40,4.49,0,10000,2.06,110,"[{'id': 800, 'main': 'Clear', 'description': '..."
11,2021-04-25 11:00:00,19.27,16.77,1016,35,3.45,0,10000,1.54,0,"[{'id': 800, 'main': 'Clear', 'description': '..."
12,2021-04-25 12:00:00,20.04,18.05,1016,40,6.04,0,10000,1.54,0,"[{'id': 800, 'main': 'Clear', 'description': '..."
13,2021-04-25 13:00:00,20.89,17.94,1015,35,4.87,0,10000,2.57,220,"[{'id': 800, 'main': 'Clear', 'description': '..."
14,2021-04-25 14:00:00,21.04,18.47,1014,35,5.01,0,10000,2.06,250,"[{'id': 800, 'main': 'Clear', 'description': '..."
15,2021-04-25 15:00:00,20.36,17.94,1013,43,7.38,0,10000,2.57,220,"[{'id': 800, 'main': 'Clear', 'description': '..."
16,2021-04-25 16:00:00,19.78,15.58,1013,40,5.81,0,10000,4.63,230,"[{'id': 800, 'main': 'Clear', 'description': '..."
17,2021-04-25 17:00:00,18.83,15.46,1013,39,4.60,0,10000,3.09,230,"[{'id': 800, 'main': 'Clear', 'description': '..."
18,2021-04-25 18:00:00,16.37,13.32,1012,39,2.40,0,10000,2.06,250,"[{'id': 800, 'main': 'Clear', 'description': '..."
19,2021-04-25 19:00:00,15.18,12.43,1013,41,2.03,0,10000,1.54,0,"[{'id': 800, 'main': 'Clear', 'description': '..."
20,2021-04-25 20:00:00,14.18,12.54,1014,51,4.20,0,10000,0.51,0,"[{'id': 800, 'main': 'Clear', 'description': '..."
21,2021-04-25 21:00:00,14.01,11.62,1013,51,4.04,0,10000,1.54,260,"[{'id': 800, 'main': 'Clear', 'description': '..."
22,2021-04-25 22:00:00,13.26,11.25,1013,54,4.16,0,10000,1.03,0,"[{'id': 800, 'main': 'Clear', 'description': '..."
23,2021-04-25 23:00:00,12.79,11.17,1013,71,7.67,99,10000,1.54,80,"[{'id': 804, 'main': 'Clouds', 'description': ..."

In [95]:
selected_columns = df1[["dt","temp"]] # creation nouveau DF

In [96]:
df2 = selected_columns.copy() # copie des colonnes dans nouveau DF

In [112]:
df2 = df2.set_index('dt') # création DatetimeIndex

In [113]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 24 entries, 2021-04-25 00:00:00 to 2021-04-25 23:00:00
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   temp    24 non-null     float64
dtypes: float64(1)
memory usage: 384.0 bytes

In [123]:
df3 = df2.resample('30min').interpolate().round(2)  # rééchantillonnage et interpolation

In [124]:
df3

                      temp
dt
2021-04-25 00:00:00  10.41
2021-04-25 00:30:00  10.32
2021-04-25 01:00:00  10.22
2021-04-25 01:30:00   9.68
2021-04-25 02:00:00   9.14
2021-04-25 02:30:00   8.94
2021-04-25 03:00:00   8.73
2021-04-25 03:30:00   8.54
2021-04-25 04:00:00   8.36
2021-04-25 04:30:00   8.25
2021-04-25 05:00:00   8.13
2021-04-25 05:30:00   9.30
2021-04-25 06:00:00  10.48
2021-04-25 06:30:00  11.80
2021-04-25 07:00:00  13.12
2021-04-25 07:30:00  14.07
2021-04-25 08:00:00  15.02
2021-04-25 08:30:00  15.86
2021-04-25 09:00:00  16.70
2021-04-25 09:30:00  17.50
2021-04-25 10:00:00  18.31
2021-04-25 10:30:00  18.79
2021-04-25 11:00:00  19.27
2021-04-25 11:30:00  19.66
2021-04-25 12:00:00  20.04
2021-04-25 12:30:00  20.46
2021-04-25 13:00:00  20.89
2021-04-25 13:30:00  20.96
2021-04-25 14:00:00  21.04
2021-04-25 14:30:00  20.70
2021-04-25 15:00:00  20.36
2021-04-25 15:30:00  20.07
2021-04-25 16:00:00  19.78
2021-04-25 16:30:00  19.30
2021-04-25 17:00:00  18.83
2021-04-25 17:30:00  17.60
2021-04-25 18:00:00  16.37
2021-04-25 18:30:00  15.78
2021-04-25 19:00:00  15.18
2021-04-25 19:30:00  14.68
2021-04-25 20:00:00  14.18
2021-04-25 20:30:00  14.10
2021-04-25 21:00:00  14.01
2021-04-25 21:30:00  13.64
2021-04-25 22:00:00  13.26
2021-04-25 22:30:00  13.02
2021-04-25 23:00:00  12.79

In [125]:
with open(r"temp_ext_ok.csv", "a") as f:
    df3.to_csv(f, header=f.tell()==0, index = True) #La méthode tell() de l’objet fichier retourne la position actuelle du curseur. Par conséquent, si le fichier est vide ou n’existe pas, f.tell==0 est True, de sorte que header est mis à True ; sinon, header est mis à False.