In [56]:
import datetime
import requests as re
import pandas as pd
import json
#api = re.get("http://api.openweathermap.org/data/2.5/weather?q=Grenoble&units=metric&lang=fr&APPID=053c09565de3a966efa5b8d39b2969d9")
#api = re.get("http://api.openweathermap.org/data/2.5/weather?lat=45.187604404569896&lon=5.704903862324499&units=metric&lang=fr&APPID=053c09565de3a966efa5b8d39b2969d9") 
#api1 = re.get("http://history.openweathermap.org/data/2.5/history/city?q=Grenoble&type=hour&start=1618945200&end=1619290800&APPID=053c09565de3a966efa5b8d39b2969d9")
api2 = re.get("http://api.openweathermap.org/data/2.5/onecall/timemachine?lat=45.187604404569896&lon=5.704903862324499&units=metric&lang=fr&dt=1618905600&APPID=053c09565de3a966efa5b8d39b2969d9")
print(api2.status_code)
print(api2.json())

200
{'lat': 45.1876, 'lon': 5.7049, 'timezone': 'Europe/Paris', 'timezone_offset': 7200, 'current': {'dt': 1618905600, 'sunrise': 1618893799, 'sunset': 1618943305, 'temp': 12.84, 'feels_like': 11.06, 'pressure': 1016, 'humidity': 59, 'dew_point': 5.03, 'uvi': 5.19, 'clouds': 4, 'wind_speed': 0.94, 'wind_deg': 328, 'wind_gust': 1, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01d'}]}, 'hourly': [{'dt': 1618876800, 'temp': 7.22, 'feels_like': 5.2, 'pressure': 1018, 'humidity': 76, 'dew_point': 3.28, 'clouds': 3, 'wind_speed': 0.81, 'wind_deg': 134, 'wind_gust': 1.1, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01n'}]}, {'dt': 1618880400, 'temp': 7.22, 'feels_like': 5.2, 'pressure': 1018, 'humidity': 76, 'dew_point': 3.28, 'clouds': 3, 'wind_speed': 0.81, 'wind_deg': 134, 'wind_gust': 1.1, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01n'}]}, {'dt': 1618884000, 'temp': 7.22, 'feels_like': 5.2, 'pressure': 1018, 'humidity': 76, 'dew_point': 3.28, 'clouds': 3, 'wind_speed': 0.81, 'wind_deg': 134, 'wind_gust': 1.1, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01n'}]}, {'dt': 1618887600, 'temp': 7.22, 'feels_like': 5.2, 'pressure': 1018, 'humidity': 76, 'dew_point': 3.28, 'clouds': 3, 'wind_speed': 0.81, 'wind_deg': 134, 'wind_gust': 1.1, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01n'}]}, {'dt': 1618891200, 'temp': 7.22, 'feels_like': 5.2, 'pressure': 1018, 'humidity': 76, 'dew_point': 3.28, 'clouds': 3, 'wind_speed': 0.81, 'wind_deg': 134, 'wind_gust': 1.1, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01n'}]}, {'dt': 1618894800, 'temp': 7.22, 'feels_like': 5.2, 'pressure': 1018, 'humidity': 76, 'dew_point': 3.28, 'clouds': 3, 'wind_speed': 0.81, 'wind_deg': 134, 'wind_gust': 1.1, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01d'}]}, {'dt': 1618898400, 'temp': 7.22, 'feels_like': 5.2, 'pressure': 1018, 'humidity': 76, 'dew_point': 3.28, 'clouds': 3, 'wind_speed': 0.81, 'wind_deg': 134, 'wind_gust': 1.1, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01d'}]}, {'dt': 1618902000, 'temp': 10.37, 'feels_like': 9.04, 'pressure': 1017, 'humidity': 65, 'dew_point': 4.08, 'clouds': 4, 'wind_speed': 0.04, 'wind_deg': 252, 'wind_gust': 0.54, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01d'}]}, {'dt': 1618905600, 'temp': 12.84, 'feels_like': 11.06, 'pressure': 1016, 'humidity': 59, 'dew_point': 5.03, 'clouds': 4, 'wind_speed': 0.94, 'wind_deg': 328, 'wind_gust': 1, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01d'}]}, {'dt': 1618909200, 'temp': 14.45, 'feels_like': 12.29, 'pressure': 1015, 'humidity': 53, 'dew_point': 5, 'clouds': 4, 'wind_speed': 1.47, 'wind_deg': 321, 'wind_gust': 1.42, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01d'}]}, {'dt': 1618912800, 'temp': 15.84, 'feels_like': 13.49, 'pressure': 1014, 'humidity': 48, 'dew_point': 4.86, 'clouds': 4, 'wind_speed': 1.7, 'wind_deg': 320, 'wind_gust': 1.5, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01d'}]}, {'dt': 1618916400, 'temp': 16.9, 'feels_like': 14.43, 'pressure': 1014, 'humidity': 45, 'dew_point': 4.9, 'clouds': 5, 'wind_speed': 1.89, 'wind_deg': 316, 'wind_gust': 1.35, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01d'}]}, {'dt': 1618920000, 'temp': 17.63, 'feels_like': 14.96, 'pressure': 1013, 'humidity': 42, 'dew_point': 4.58, 'clouds': 23, 'wind_speed': 2.09, 'wind_deg': 313, 'wind_gust': 1.38, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'peu nuageux', 'icon': '02d'}]}, {'dt': 1618923600, 'temp': 18.09, 'feels_like': 15.22, 'pressure': 1012, 'humidity': 39, 'dew_point': 3.93, 'clouds': 13, 'wind_speed': 2.19, 'wind_deg': 312, 'wind_gust': 1.72, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'peu nuageux', 'icon': '02d'}]}, {'dt': 1618927200, 'temp': 15.82, 'feels_like': 12.58, 'pressure': 1013, 'humidity': 31, 'dew_point': -1.11, 'clouds': 20, 'visibility': 10000, 'wind_speed': 1.54, 'wind_deg': 300, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'peu nuageux', 'icon': '02d'}]}, {'dt': 1618930800, 'temp': 16.26, 'feels_like': 12.89, 'pressure': 1012, 'humidity': 34, 'dew_point': 0.39, 'clouds': 0, 'visibility': 10000, 'wind_speed': 2.06, 'wind_deg': 0, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01d'}]}, {'dt': 1618934400, 'temp': 16.61, 'feels_like': 12.49, 'pressure': 1012, 'humidity': 27, 'dew_point': -2.17, 'clouds': 0, 'visibility': 10000, 'wind_speed': 2.57, 'wind_deg': 290, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01d'}]}, {'dt': 1618938000, 'temp': 15.16, 'feels_like': 11.65, 'pressure': 1012, 'humidity': 34, 'dew_point': -0.51, 'clouds': 0, 'visibility': 10000, 'wind_speed': 2.06, 'wind_deg': 360, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01d'}]}, {'dt': 1618941600, 'temp': 13.02, 'feels_like': 9.54, 'pressure': 1013, 'humidity': 47, 'dew_point': 1.98, 'clouds': 0, 'visibility': 10000, 'wind_speed': 2.57, 'wind_deg': 340, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01d'}]}, {'dt': 1618945200, 'temp': 10.22, 'feels_like': 7, 'pressure': 1013, 'humidity': 54, 'dew_point': 1.33, 'clouds': 0, 'visibility': 10000, 'wind_speed': 2.06, 'wind_deg': 10, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01n'}]}, {'dt': 1618948800, 'temp': 10.09, 'feels_like': 7.49, 'pressure': 1014, 'humidity': 61, 'dew_point': 2.92, 'clouds': 0, 'visibility': 10000, 'wind_speed': 1.54, 'wind_deg': 150, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01n'}]}, {'dt': 1618952400, 'temp': 9.83, 'feels_like': 6.03, 'pressure': 1013, 'humidity': 50, 'dew_point': -0.08, 'clouds': 90, 'visibility': 10000, 'wind_speed': 2.57, 'wind_deg': 180, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'couvert', 'icon': '04n'}]}, {'dt': 1618956000, 'temp': 7.99, 'feels_like': 4.38, 'pressure': 1014, 'humidity': 62, 'dew_point': 1.16, 'clouds': 0, 'visibility': 10000, 'wind_speed': 2.57, 'wind_deg': 280, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01n'}]}, {'dt': 1618959600, 'temp': 7.21, 'feels_like': 4.9, 'pressure': 1014, 'humidity': 61, 'dew_point': 0.2, 'clouds': 0, 'visibility': 10000, 'wind_speed': 0.51, 'wind_deg': 0, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'ciel dégagé', 'icon': '01n'}]}]}

In [34]:
api2.text 
data_dict = api2.json()

In [35]:
with open("data_file.json", "w") as write_file:
    json.dump(data_dict, write_file)

In [53]:
#print(data_dict['main']['temp'] , data_dict['main']['feels_like'], data_dict['main']['temp_min'], data_dict['main']['temp_max'])
print(data_dict['current']['dt'], data_dict['current']['temp'])

1618905600 12.84

In [55]:
df1 = pd.json_normalize(data_dict['hourly'])
df1

,dt,temp,feels_like,pressure,humidity,dew_point,clouds,wind_speed,wind_deg,wind_gust,weather,visibility
0,1618876800,5.74,3.45,1018,88,3.91,4,1.36,132,1.24,"[{'id': 800, 'main': 'Clear', 'description': '...",NaN
1,1618880400,5.35,3.00,1018,88,3.53,6,1.34,131,1.23,"[{'id': 800, 'main': 'Clear', 'description': '...",NaN
2,1618884000,5.11,2.74,1018,88,3.29,6,1.32,133,1.23,"[{'id': 800, 'main': 'Clear', 'description': '...",NaN
3,1618887600,4.86,2.42,1018,88,3.04,6,1.35,135,1.21,"[{'id': 800, 'main': 'Clear', 'description': '...",NaN
4,1618891200,4.60,2.12,1018,88,2.79,6,1.35,132,1.23,"[{'id': 800, 'main': 'Clear', 'description': '...",NaN
5,1618894800,4.57,2.07,1018,87,2.60,5,1.33,128,1.23,"[{'id': 800, 'main': 'Clear', 'description': '...",NaN
6,1618898400,7.22,5.20,1018,76,3.28,3,0.81,134,1.10,"[{'id': 800, 'main': 'Clear', 'description': '...",NaN
7,1618902000,10.37,9.04,1017,65,4.08,4,0.04,252,0.54,"[{'id': 800, 'main': 'Clear', 'description': '...",NaN
8,1618905600,12.84,11.06,1016,59,5.03,4,0.94,328,1.00,"[{'id': 800, 'main': 'Clear', 'description': '...",NaN
9,1618909200,11.97,9.55,1015,50,1.88,0,1.03,0,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",10000.0
10,1618912800,13.70,11.26,1015,51,3.76,0,1.54,0,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",10000.0
11,1618916400,15.16,12.58,1014,44,3.00,0,1.54,0,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",10000.0
12,1618920000,17.07,14.13,1013,39,3.02,20,2.06,20,NaN,"[{'id': 801, 'main': 'Clouds', 'description': ...",10000.0
13,1618923600,16.84,13.31,1013,36,1.70,20,2.57,0,NaN,"[{'id': 801, 'main': 'Clouds', 'description': ...",10000.0
14,1618927200,15.82,12.58,1013,31,-1.11,20,1.54,300,NaN,"[{'id': 801, 'main': 'Clouds', 'description': ...",10000.0
15,1618930800,16.26,12.89,1012,34,0.39,0,2.06,0,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",10000.0
16,1618934400,16.61,12.49,1012,27,-2.17,0,2.57,290,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",10000.0
17,1618938000,15.16,11.65,1012,34,-0.51,0,2.06,360,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",10000.0
18,1618941600,13.02,9.54,1013,47,1.98,0,2.57,340,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",10000.0
19,1618945200,10.22,7.00,1013,54,1.33,0,2.06,10,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",10000.0
20,1618948800,10.09,7.49,1014,61,2.92,0,1.54,150,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",10000.0
21,1618952400,9.83,6.03,1013,50,-0.08,90,2.57,180,NaN,"[{'id': 804, 'main': 'Clouds', 'description': ...",10000.0
22,1618956000,7.99,4.38,1014,62,1.16,0,2.57,280,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",10000.0
23,1618959600,7.21,4.90,1014,61,0.20,0,0.51,0,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",10000.0

In [40]:
print(df1.columns.values)

['dt' 'sunrise' 'sunset' 'temp' 'feels_like' 'pressure' 'humidity'
 'dew_point' 'uvi' 'clouds' 'wind_speed' 'wind_deg' 'wind_gust' 'weather']

In [41]:
for column in df1:
    print(df1[column])

0    1618905600
Name: dt, dtype: int64
0    1618893799
Name: sunrise, dtype: int64
0    1618943305
Name: sunset, dtype: int64
0    12.84
Name: temp, dtype: float64
0    11.06
Name: feels_like, dtype: float64
0    1016
Name: pressure, dtype: int64
0    59
Name: humidity, dtype: int64
0    5.03
Name: dew_point, dtype: float64
0    5.19
Name: uvi, dtype: float64
0    4
Name: clouds, dtype: int64
0    0.94
Name: wind_speed, dtype: float64
0    328
Name: wind_deg, dtype: int64
0    1
Name: wind_gust, dtype: int64
0    [{'id': 800, 'main': 'Clear', 'description': '...
Name: weather, dtype: object

In [42]:
for column in df1.itertuples():
  print(column.temp)

12.84